server:
  port: 8082
  servlet:
    context-path: /altatest
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:hsqldb:hsql://localhost:9001/sampleDB
    username: SA
    password:
    driverClassName: org.hsqldb.jdbcDriver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
#      hbm2ddl.method: create-drop
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.HSQLDialect

